// OpenAPIContractTests.swift  (Phase 0 · U84)
//
// Contract test: load the backend's OpenAPI 3.1 snapshot and assert each
// curated iOS Codable DTO can decode a payload synthesised from its
// corresponding schema's `required` fields.
//
// If the backend adds a non-optional response field that the matching
// Swift DTO doesn't model, the synthesised payload includes the new key
// and `JSONDecoder.decode` ignores it cleanly — so missing-on-iOS
// detection isn't the main signal here. The main signal is the inverse:
// if the iOS DTO declares a NON-OPTIONAL property that the OpenAPI
// `required[]` list no longer contains, the synthesised payload omits
// the key and Swift's decode throws `.keyNotFound`. Tests catch this at
// CI time instead of runtime in production.
//
// The snapshot is regenerated by `npm run openapi:snapshot` (see
// `scripts/export-openapi-snapshot.ts`). Run it whenever the backend
// schemas change; commit the resulting `openapi-snapshot.json`. CI
// should also run the script and `git diff --exit-code` the result to
// catch a backend schema change that landed without snapshot refresh.
//
// Plan reference: docs/plans/2026-05-09-001-feat-ios-swiftui-kolaleaf-mobile-app-plan.md
// (lines 2268–2279).

import XCTest

@testable import Kolaleaf

final class OpenAPIContractTests: XCTestCase {

    // MARK: - Setup

    private var spec: OpenAPISpec!
    private var decoder: JSONDecoder!

    override func setUpWithError() throws {
        try super.setUpWithError()

        let bundle = Bundle(for: type(of: self))
        guard let url = bundle.url(forResource: "openapi-snapshot", withExtension: "json") else {
            XCTFail(
                "openapi-snapshot.json not bundled into KolaleafTests resources. "
                + "Regenerate with `npm run openapi:snapshot` and verify "
                + "ios/project.yml lists it under the KolaleafTests target."
            )
            return
        }
        let data = try Data(contentsOf: url)
        spec = try JSONDecoder().decode(OpenAPISpec.self, from: data)

        // Match the production APIClient decoder so date-bearing DTOs
        // (`TransferShape.payidExpiresAt`, `RatePublicResponse.effectiveAt`)
        // decode against the synthesised ISO-8601 placeholders.
        decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
    }

    // MARK: - Auth

    func test_sendCodeResponse_matchesBackendSchema() throws {
        try assertDecodes(
            SendCodeResponse.self,
            path: "/auth/send-code", method: "post", status: "200",
            knownKeys: ["ok"]
        )
    }

    func test_verifyCodeResponse_matchesBackendSchema() throws {
        try assertDecodes(
            VerifyCodeResponse.self,
            path: "/auth/verify-code", method: "post", status: "200",
            knownKeys: ["verified"]
        )
    }

    func test_loginResponse_matchesBackendSchema() throws {
        try assertDecodes(
            LoginResponse.self,
            path: "/auth/login", method: "post", status: "200",
            // `requires2FA` is the wire name; `twoFactorMethod` is optional.
            knownKeys: ["user", "requires2FA", "twoFactorMethod"]
        )
    }

    func test_completeRegistrationResponse_matchesBackendSchema() throws {
        try assertDecodes(
            CompleteRegistrationResponse.self,
            path: "/auth/complete-registration", method: "post", status: "201",
            knownKeys: ["user"]
        )
    }

    // MARK: - Account

    func test_meResponse_matchesBackendSchema() throws {
        try assertDecodes(
            MeResponse.self,
            path: "/account/me", method: "get", status: "200",
            knownKeys: [
                "userId", "fullName", "displayName",
                "primaryEmail", "email", // `email` is the legacy alias the DTO still accepts
                "secondaryEmails",
                "twoFactorMethod", "twoFactorEnabledAt",
                "hasVerifiedPhone", "phoneMasked",
                "hasRemainingBackupCodes", "backupCodesRemaining",
                "addressLine1", "addressLine2", "city", "state",
                "postcode", "country", "kycStatus",
            ]
        )
    }

    func test_enableTwoFactorResponse_matchesBackendSchema() throws {
        try assertDecodes(
            EnableTwoFactorResponse.self,
            path: "/account/2fa/enable", method: "post", status: "200",
            knownKeys: ["enabled", "backupCodes"]
        )
    }

    // MARK: - KYC

    func test_kycInitiateResponse_matchesBackendSchema() throws {
        try assertDecodes(
            KycInitiateResponse.self,
            path: "/kyc/initiate", method: "post", status: "200",
            knownKeys: ["applicantId", "accessToken", "verificationUrl"]
        )
    }

    func test_kycStatusResponse_matchesBackendSchema() throws {
        try assertDecodes(
            KycStatusResponse.self,
            path: "/kyc/status", method: "get", status: "200",
            knownKeys: ["status", "applicantId"]
        )
    }

    // MARK: - Transfers

    func test_createTransferResponse_matchesBackendSchema() throws {
        try assertDecodes(
            CreateTransferResponse.self,
            path: "/transfers", method: "post", status: "201",
            knownKeys: ["transfer"]
        )
    }

    func test_listTransfersResponse_matchesBackendSchema() throws {
        try assertDecodes(
            ListTransfersResponse.self,
            path: "/transfers", method: "get", status: "200",
            knownKeys: ["transfers", "nextCursor"]
        )
    }

    // MARK: - Recipients

    func test_recipientsListResponse_matchesBackendSchema() throws {
        try assertDecodes(
            RecipientsListResponse.self,
            path: "/recipients", method: "get", status: "200",
            knownKeys: ["recipients"]
        )
    }

    func test_createRecipientResponse_matchesBackendSchema() throws {
        try assertDecodes(
            CreateRecipientResponse.self,
            path: "/recipients", method: "post", status: "201",
            knownKeys: ["recipient"]
        )
    }

    func test_resolveRecipientResponse_matchesBackendSchema() throws {
        try assertDecodes(
            ResolveRecipientResponse.self,
            path: "/recipients/resolve", method: "post", status: "200",
            knownKeys: ["accountName"]
        )
    }

    // MARK: - Rates

    func test_ratePublicResponse_matchesBackendSchema() throws {
        try assertDecodes(
            RatePublicResponse.self,
            path: "/rates/public", method: "get", status: "200",
            knownKeys: [
                "baseCurrency", "targetCurrency",
                "corridorId", "customerRate", "effectiveAt",
            ]
        )
    }

    // MARK: - Drift-detection harness invariants
    //
    // Sanity check: the synthesiser produces stable output for the
    // SAME schema across calls and includes EVERY `required` key.
    // If this test ever fails the harness is buggy, not the DTOs.

    func test_synthesiser_includesEveryRequiredKey() throws {
        let schema = try schemaFor(path: "/account/me", method: "get", status: "200")
        let payload = try OpenAPIPayloadSynth.synthesise(schema: schema, spec: spec)
        guard case .object(let dict) = payload else {
            return XCTFail("Expected object payload for /account/me 200")
        }
        for required in schema.required ?? [] {
            XCTAssertNotNil(
                dict[required],
                "Synthesiser dropped required key '\(required)' for /account/me 200"
            )
        }
    }

    // MARK: - Helpers

    /// Looks up the schema for a (path, method, status) triple, synthesises a
    /// JSON payload that contains every `required` field, and tries to decode
    /// it as `T`. Decode failure is a hard contract drift signal.
    ///
    /// `knownKeys` is the set of top-level JSON keys the iOS DTO is capable
    /// of reading (Codable property names, plus any legacy aliases the
    /// custom decoder accepts). The test asserts every `required` key in
    /// the OpenAPI schema is in `knownKeys` — that's the assertion that
    /// catches "backend added a required field iOS doesn't model" at CI
    /// time. `JSONDecoder` would otherwise silently ignore the new field
    /// and the drift would only surface at runtime.
    private func assertDecodes<T: Decodable>(
        _ type: T.Type,
        path: String,
        method: String,
        status: String,
        knownKeys: Set<String>,
        file: StaticString = #file,
        line: UInt = #line
    ) throws {
        let schema = try schemaFor(
            path: path, method: method, status: status,
            file: file, line: line
        )

        // Coverage check: every required key in the backend schema must
        // appear in the iOS DTO's known-key set. A newly-required field
        // that's absent here is the drift this whole suite is built to
        // catch (the production failure the plan calls out at U84).
        let required = Set(schema.required ?? [])
        let missing = required.subtracting(knownKeys)
        if !missing.isEmpty {
            XCTFail(
                """
                Contract drift: \(T.self) is missing required key(s) the backend \
                declares for \(method.uppercased()) \(path) \(status): \
                \(missing.sorted().joined(separator: ", ")).

                The backend OpenAPI schema requires these fields, but the iOS DTO \
                does not declare them. Add the property to the Swift DTO (or its \
                CodingKeys), then update this test's `knownKeys` set.
                """,
                file: file, line: line
            )
            // Fall through to also run the decode check — the failure
            // message above is the primary signal but the decode-time
            // diagnostic below is still useful when the missing field
            // shape is what's confusing.
        }

        let payload: OpenAPIPayloadSynth.JSONValue
        do {
            payload = try OpenAPIPayloadSynth.synthesise(schema: schema, spec: spec)
        } catch {
            XCTFail(
                "Failed to synthesise payload for \(method.uppercased()) \(path) \(status): \(error)",
                file: file, line: line
            )
            return
        }

        let data: Data
        do {
            data = try payload.encoded()
        } catch {
            XCTFail(
                "Failed to encode synthesised payload for \(method.uppercased()) \(path) \(status): \(error)",
                file: file, line: line
            )
            return
        }

        do {
            _ = try decoder.decode(T.self, from: data)
        } catch {
            let pretty = String(data: data, encoding: .utf8) ?? "<unprintable>"
            XCTFail(
                """
                Contract drift: \(T.self) failed to decode the synthesised payload \
                for \(method.uppercased()) \(path) \(status).

                The backend OpenAPI schema and this iOS DTO have drifted. Either \
                update the Swift DTO to match the new contract, or regenerate the \
                snapshot if the backend hasn't shipped yet.

                Decode error: \(error)

                Synthesised payload:
                \(pretty)
                """,
                file: file, line: line
            )
        }
    }

    private func schemaFor(
        path: String,
        method: String,
        status: String,
        file: StaticString = #file,
        line: UInt = #line
    ) throws -> OpenAPISchema {
        guard let pathItem = spec.paths[path] else {
            XCTFail("OpenAPI snapshot has no path '\(path)'", file: file, line: line)
            throw ContractError.missingPath(path)
        }
        guard let op = pathItem.operation(for: method) else {
            XCTFail(
                "OpenAPI snapshot has no \(method.uppercased()) operation at '\(path)'",
                file: file, line: line
            )
            throw ContractError.missingOperation(path: path, method: method)
        }
        guard let response = op.responses[status] else {
            XCTFail(
                "OpenAPI snapshot has no \(status) response for \(method.uppercased()) '\(path)'",
                file: file, line: line
            )
            throw ContractError.missingResponse(path: path, method: method, status: status)
        }
        guard let schema = response.content?["application/json"]?.schema else {
            XCTFail(
                "OpenAPI snapshot has no application/json schema for \(method.uppercased()) '\(path)' \(status)",
                file: file, line: line
            )
            throw ContractError.missingSchema(path: path, method: method, status: status)
        }
        return schema
    }

    private enum ContractError: Error {
        case missingPath(String)
        case missingOperation(path: String, method: String)
        case missingResponse(path: String, method: String, status: String)
        case missingSchema(path: String, method: String, status: String)
    }
}

// MARK: - Minimal OpenAPI 3.1 model
//
// Only models the fields we actually read. Everything else is decoded
// lazily through `additionalProperties` so a future spec field doesn't
// blow up the snapshot decode.

struct OpenAPISpec: Decodable {
    let openapi: String
    let paths: [String: OpenAPIPathItem]
    let components: OpenAPIComponents?
}

struct OpenAPIPathItem: Decodable {
    let get: OpenAPIOperation?
    let post: OpenAPIOperation?
    let put: OpenAPIOperation?
    let patch: OpenAPIOperation?
    let delete: OpenAPIOperation?

    func operation(for method: String) -> OpenAPIOperation? {
        switch method.lowercased() {
        case "get": return get
        case "post": return post
        case "put": return put
        case "patch": return patch
        case "delete": return delete
        default: return nil
        }
    }
}

struct OpenAPIOperation: Decodable {
    let responses: [String: OpenAPIResponse]
}

struct OpenAPIResponse: Decodable {
    let content: [String: OpenAPIMediaType]?
}

struct OpenAPIMediaType: Decodable {
    let schema: OpenAPISchema?
}

struct OpenAPIComponents: Decodable {
    let schemas: [String: OpenAPISchema]?
}

/// A pragmatic subset of OpenAPI 3.1 / JSON Schema.
///
/// Implemented as a `final class` rather than a `struct` because schemas
/// recursively contain themselves (`items`, `properties`, `oneOf`, etc.)
/// and Swift can't size a value type with a stored property whose type
/// is or transitively contains itself. A reference type sidesteps the
/// "infinite size" diagnostic without the `indirect` enum dance.
///
/// The `type` field in OpenAPI 3.1 may be a string OR an array of
/// strings (nullable shorthand), so we keep both shapes via
/// `OpenAPISchemaType`.
final class OpenAPISchema: Decodable {
    let type: OpenAPISchemaType?
    let format: String?
    let items: OpenAPISchema?
    let properties: [String: OpenAPISchema]?
    let required: [String]?
    let `enum`: [AnyCodable]?
    let example: AnyCodable?
    let oneOf: [OpenAPISchema]?
    let anyOf: [OpenAPISchema]?
    let allOf: [OpenAPISchema]?
    let ref: String?

    private enum CodingKeys: String, CodingKey {
        case type, format, items, properties, required
        case `enum`, example
        case oneOf, anyOf, allOf
        case ref = "$ref"
    }

    init(
        type: OpenAPISchemaType?,
        format: String?,
        items: OpenAPISchema?,
        properties: [String: OpenAPISchema]?,
        required: [String]?,
        enum: [AnyCodable]?,
        example: AnyCodable?,
        oneOf: [OpenAPISchema]?,
        anyOf: [OpenAPISchema]?,
        allOf: [OpenAPISchema]?,
        ref: String?
    ) {
        self.type = type
        self.format = format
        self.items = items
        self.properties = properties
        self.required = required
        self.`enum` = `enum`
        self.example = example
        self.oneOf = oneOf
        self.anyOf = anyOf
        self.allOf = allOf
        self.ref = ref
    }

    required init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.type = try c.decodeIfPresent(OpenAPISchemaType.self, forKey: .type)
        self.format = try c.decodeIfPresent(String.self, forKey: .format)
        self.items = try c.decodeIfPresent(OpenAPISchema.self, forKey: .items)
        self.properties = try c.decodeIfPresent([String: OpenAPISchema].self, forKey: .properties)
        self.required = try c.decodeIfPresent([String].self, forKey: .required)
        self.`enum` = try c.decodeIfPresent([AnyCodable].self, forKey: .`enum`)
        self.example = try c.decodeIfPresent(AnyCodable.self, forKey: .example)
        self.oneOf = try c.decodeIfPresent([OpenAPISchema].self, forKey: .oneOf)
        self.anyOf = try c.decodeIfPresent([OpenAPISchema].self, forKey: .anyOf)
        self.allOf = try c.decodeIfPresent([OpenAPISchema].self, forKey: .allOf)
        self.ref = try c.decodeIfPresent(String.self, forKey: .ref)
    }
}

/// `type` is either a single string ("object") or an array of strings
/// (`["string", "null"]` — the OpenAPI 3.1 nullable shorthand).
enum OpenAPISchemaType: Decodable {
    case single(String)
    case multiple([String])

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if let one = try? c.decode(String.self) {
            self = .single(one)
        } else {
            self = .multiple(try c.decode([String].self))
        }
    }

    /// Returns the "primary" type for synthesis — the first non-"null"
    /// entry if multiple types are listed.
    var primary: String? {
        switch self {
        case .single(let s): return s
        case .multiple(let arr):
            return arr.first(where: { $0 != "null" }) ?? arr.first
        }
    }

    var isNullable: Bool {
        switch self {
        case .single: return false
        case .multiple(let arr): return arr.contains("null")
        }
    }
}

/// A pass-through Decodable that captures any JSON value (number / string /
/// bool / null) without committing to a concrete type. Used for `example`
/// and `enum` payloads in the snapshot.
struct AnyCodable: Decodable {
    let value: Any

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() {
            self.value = NSNull()
        } else if let b = try? c.decode(Bool.self) {
            self.value = b
        } else if let i = try? c.decode(Int.self) {
            self.value = i
        } else if let d = try? c.decode(Double.self) {
            self.value = d
        } else if let s = try? c.decode(String.self) {
            self.value = s
        } else if let arr = try? c.decode([AnyCodable].self) {
            self.value = arr.map(\.value)
        } else if let obj = try? c.decode([String: AnyCodable].self) {
            self.value = obj.mapValues(\.value)
        } else {
            self.value = NSNull()
        }
    }
}

// MARK: - Payload synthesiser
//
// Given an `OpenAPISchema`, generate a JSON payload that includes every
// `required` field with a type-correct placeholder. Iterating only over
// `required` (not all `properties`) mirrors the contract guarantee — the
// payload is the minimum a conforming server must emit.

enum OpenAPIPayloadSynth {

    enum SynthError: Error, CustomStringConvertible {
        case unsupportedSchema(String)

        var description: String {
            switch self {
            case .unsupportedSchema(let msg): return "Unsupported schema: \(msg)"
            }
        }
    }

    /// Lightweight JSON value model. Built explicitly so encoding is
    /// deterministic — `JSONSerialization` on an `[String: Any]` from a
    /// `[String: AnyCodable]` would lose key order, which complicates
    /// debugging when a test fails.
    indirect enum JSONValue {
        case null
        case bool(Bool)
        case int(Int)
        case double(Double)
        case string(String)
        case array([JSONValue])
        case object([String: JSONValue])

        func encoded() throws -> Data {
            try JSONSerialization.data(
                withJSONObject: asObject(),
                options: [.fragmentsAllowed, .sortedKeys]
            )
        }

        private func asObject() -> Any {
            switch self {
            case .null: return NSNull()
            case .bool(let b): return b
            case .int(let i): return i
            case .double(let d): return d
            case .string(let s): return s
            case .array(let a): return a.map { $0.asObject() }
            case .object(let o):
                var out: [String: Any] = [:]
                for (k, v) in o { out[k] = v.asObject() }
                return out
            }
        }
    }

    static func synthesise(
        schema: OpenAPISchema,
        spec: OpenAPISpec
    ) throws -> JSONValue {
        // $ref resolution against components/schemas.
        if let ref = schema.ref {
            let key = ref.replacingOccurrences(of: "#/components/schemas/", with: "")
            if let resolved = spec.components?.schemas?[key] {
                return try synthesise(schema: resolved, spec: spec)
            }
            throw SynthError.unsupportedSchema("Unresolvable $ref: \(ref)")
        }

        // Unions: pick the first variant. The synth's only job is to
        // produce SOMETHING decodable — call sites can add union-specific
        // tests if they need exhaustive coverage.
        if let oneOf = schema.oneOf, let first = oneOf.first {
            return try synthesise(schema: first, spec: spec)
        }
        if let anyOf = schema.anyOf, let first = anyOf.first {
            return try synthesise(schema: first, spec: spec)
        }
        if let allOf = schema.allOf {
            // Merge required fields and property maps from each branch.
            var mergedProps: [String: OpenAPISchema] = [:]
            var mergedRequired: [String] = []
            for sub in allOf {
                for (k, v) in sub.properties ?? [:] { mergedProps[k] = v }
                mergedRequired.append(contentsOf: sub.required ?? [])
            }
            let merged = OpenAPISchema(
                type: .single("object"),
                format: nil,
                items: nil,
                properties: mergedProps,
                required: mergedRequired,
                enum: nil,
                example: nil,
                oneOf: nil,
                anyOf: nil,
                allOf: nil,
                ref: nil
            )
            return try synthesise(schema: merged, spec: spec)
        }

        // Enums: emit the first enum value.
        if let cases = schema.`enum`, let first = cases.first {
            return wrap(first.value)
        }

        // Examples are NOT used to drive placeholder values — they
        // sometimes show optional shapes that omit `required` keys, which
        // would defeat the test. Synthesis from type+required is the
        // contract-tight path.

        switch schema.type?.primary {
        case "object":
            var out: [String: JSONValue] = [:]
            for key in schema.required ?? [] {
                guard let prop = schema.properties?[key] else {
                    // Required key without a properties entry — emit a
                    // string so encoder doesn't bail. This is rare and
                    // usually means the schema is `.passthrough()` style.
                    out[key] = .string("placeholder")
                    continue
                }
                // Property-name heuristic for timestamps: backend Zod
                // schemas frequently use `z.string()` for timestamp
                // fields without the `.datetime()` refinement, so
                // `format: date-time` is absent from the snapshot.
                // The iOS DTOs still decode these as `Date` via the
                // ISO8601 strategy, so for plain string properties
                // whose names conventionally carry a timestamp
                // (`*At`, `*Date`, `effectiveAt`) emit an ISO-8601
                // placeholder. This avoids false positives without
                // touching the canonical synthesis path.
                if prop.type?.primary == "string"
                    && prop.format == nil
                    && Self.looksLikeTimestampKey(key) {
                    out[key] = .string("2026-01-01T00:00:00Z")
                } else {
                    out[key] = try synthesise(schema: prop, spec: spec)
                }
            }
            return .object(out)

        case "array":
            // Emit a single-element array of the item shape, so list
            // DTOs (e.g. RecipientsListResponse) exercise their nested
            // decoder.
            if let item = schema.items {
                return .array([try synthesise(schema: item, spec: spec)])
            }
            return .array([])

        case "string":
            return .string(stringPlaceholder(format: schema.format))

        case "integer":
            return .int(0)

        case "number":
            return .double(0)

        case "boolean":
            return .bool(false)

        case "null":
            return .null

        case .none:
            // Schemas with no `type` and no enum/composition can happen
            // for `.passthrough()` style sub-objects. Treat as an empty
            // object — the surrounding decoder will tolerate it.
            return .object([:])

        case .some(let other):
            throw SynthError.unsupportedSchema("type=\(other)")
        }
    }

    /// Heuristic: does this property name conventionally carry an
    /// ISO-8601 timestamp? Used when the backend schema is plain
    /// `z.string()` (so no `format: date-time` lands in the spec)
    /// but the iOS DTO decodes the field as a `Date`.
    static func looksLikeTimestampKey(_ key: String) -> Bool {
        if key.hasSuffix("At") { return true }
        if key.hasSuffix("Date") { return true }
        return false
    }

    /// Generates a placeholder that satisfies common `format` strings.
    /// Add cases as new formats appear in the snapshot.
    private static func stringPlaceholder(format: String?) -> String {
        switch format {
        case "date-time": return "2026-01-01T00:00:00Z"
        case "date":      return "2026-01-01"
        case "email":     return "placeholder@example.com"
        case "uuid":      return "00000000-0000-0000-0000-000000000000"
        case "uri", "url": return "https://example.com/"
        default:          return "placeholder"
        }
    }

    /// Wraps an `AnyCodable` value (from enum) back into our JSONValue.
    private static func wrap(_ v: Any) -> JSONValue {
        if v is NSNull { return .null }
        if let b = v as? Bool { return .bool(b) }
        if let i = v as? Int { return .int(i) }
        if let d = v as? Double { return .double(d) }
        if let s = v as? String { return .string(s) }
        if let arr = v as? [Any] { return .array(arr.map(wrap)) }
        if let obj = v as? [String: Any] {
            var out: [String: JSONValue] = [:]
            for (k, val) in obj { out[k] = wrap(val) }
            return .object(out)
        }
        return .null
    }
}
